# Generated by Django 5.2.5 on 2025-09-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ip', 'IP Fraud Detection'), ('email', 'Email Fraud Detection'), ('phone', 'Phone Fraud Detection'), ('custom', 'Custom API')], default='Phone Fraud Detection', max_length=20)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
