# Generated by Django 5.2.5 on 2025-09-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('seller_supplier_order_unique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_link', models.URLField(max_length=2083, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_link', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ResellerOrderTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_link', models.URLField(max_length=2083, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_link', to='seller_supplier_order_unique.sellersupplierorder')),
            ],
        ),
    ]
