# Generated by Django 5.2.5 on 2025-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailer', models.CharField(choices=[('smtp', 'SMTP'), ('sendmail', 'Sendmail'), ('mailgun', 'Mailgun'), ('ses', 'Amazon SES'), ('postmark', 'Postmark'), ('sparkpost', 'SparkPost')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('encryption', models.CharField(choices=[('ssl', 'SSL'), ('tls', 'TLS'), ('none', 'None')], default='none', max_length=50)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
            ],
        ),
    ]
