# Generated by Django 5.2.5 on 2025-09-16 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_sales_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=95.0, help_text='Reseller commission percentage', max_digits=5)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user_requested_amount_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
