# Generated by Django 5.2.5 on 2025-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('white_logo', models.ImageField(upload_to='logos/white/')),
                ('dark_logo', models.ImageField(upload_to='logos/dark/')),
                ('favicon', models.ImageField(upload_to='favicons/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
